from setuptools import setup, find_packages

setup(
    name="PathRAG",
    version="0.1.0",
    description="PathRAG: Pruning Graph-based Retrieval Augmented Generation with Relational Paths",
    author="PathRAG Authors",
    license="MIT",
    packages=find_packages(exclude=["web_app*", "examples*", "docs*", "tests*"]),
    python_requires=">=3.10",
    install_requires=[
        "aioboto3",
        "aiohttp",
        "graspologic",
        "nano-vectordb",
        "networkx",
        "numpy",
        "openai",
        "pydantic",
        "tenacity",
        "tiktoken",
        "tqdm",
    ],
    extras_require={
        "spanner": [
            "google-cloud-spanner",
        ],
        "huggingface": [
            "accelerate",
            "torch",
            "transformers",
        ],
        "ollama": [
            "ollama",
        ],
        "litellm": [
            "litellm",
        ],
        "vllm": [
            "vllm",
            "modelscope",
        ],
        "api": [
            "fastapi",
            "uvicorn[standard]",
            "websockets",
            "python-dotenv",
            "python-multipart",
            "python-jose",
            "passlib",
            "bcrypt",
            "pyjwt",
            "aiosqlite",
            "sqlalchemy",
            "psycopg[binary,pool]",
            "PyPDF2",
            "python-docx",
            "docx2txt",
            "python-pptx",
            "openpyxl",
            "striprtf",
            "odfpy",
            "ebooklib",
            "beautifulsoup4",
            "matplotlib",
        ],
        "all": [
            "PathRAG[spanner,huggingface,ollama,litellm,vllm,api]",
        ],
    },
)
